package status

const (
	//Success ...
	Success = 200
	//Error ...
	Error = 500
	//InvalidParams ...
	InvalidParams = 400
	//ErrorExistTag ...
	ErrorExistTag = 10001
	//ErrorNotExistTag ...
	ErrorNotExistTag = 10002
	//ErrorNotExistArticle ...
	ErrorNotExistArticle = 10003
	//ErrorExistUser ...
	ErrorExistUser = 10004
	//ErrorNotExistUser ...
	ErrorNotExistUser = 10005
	//ErrorPassword ...
	ErrorPassword = 10006
	//ErrorAuthCheckTokenFail ...
	ErrorAuthCheckTokenFail = 20001
	//ErrorAuthCheckTokenTimeout ...
	ErrorAuthCheckTokenTimeout = 20002
	//ErrorAuthToken ...
	ErrorAuthToken = 20003
	//ErrorAuth ...
	ErrorAuth = 20004
	//ErrorUploadSaveImageFail ...
	ErrorUploadSaveImageFail = 30001
	//ErrorUploadCheckImageFail ...
	ErrorUploadCheckImageFail = 30002
	//ErrorUploadCheckImageFormat ...
	ErrorUploadCheckImageFormat = 30003
)
